[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lookout-for-equipment-demo-app"
authors = [{name = "Michaël HOARAU", email = "michoara@amazon.fr"}]
dynamic = ["version", "description"]
